version: "3"

services:
  influxdb:
    image: influxdb:1.5-alpine
    ports:
      - "8086:8086"
    networks:
      - tig
    volumes:
      - "./influxdb:/var/lib/influxdb"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - tig
    volumes:
      - "./grafana:/var/lib/grafana"
  telegraf:
    image: telegraf:1.5-alpine
    ports:
      - "8125:8125"
    networks:
      - tig
    volumes:
      - "./telegraf.conf:/etc/telegraf/telegraf.conf"

networks:
  tig:
